### ISSUE TITLE
Support for SRID transformations?

### ISSUE THREAD

**Issue by abmohan** [mbostock/shapefile#14]
Thanks for developing this tool!

I'm using it to import Canadian electoral districts into MongoDB. Here's a sample file: http://ftp2.cits.rncan.gc.ca/pub/geott/electoral/2011/fed308.2011.zip

The shapefile is in NAD83 CNT and the points have to be transformed to WGS84 for visualization. Are you planning on implementing a tool that performs such calculations, and if not, would you be willing to incorporate one if it were to be written?

**Comment by calvinmetcalf** [comment]
since it turns it into geojson you can use something like https://github.com/calvinmetcalf/proj4geojson to convert the geojson

**Comment by mbostock** [comment]
Sorry for not replying this issue. This is just a Shapefile parser, so it wouldn’t be the right place to implement coordinate system transformations. I’d either use ogr2ogr for that or a GeoJSON-based tool as Calvin suggested. Hope you figured something out already. 😉

**Comment by abmohan** [comment]
I did, indeed. At the time, I used ogr2ogr. Thanks, @mbostock
