### ISSUE TITLE
Coordinate Reference System

### ISSUE THREAD

**Issue by DenisCarriere** [mbostock/shapefile#27]
The coordinate reference systems should be included at least in the `read` GeoJSON.

http://geojson.org/geojson-spec.html#coordinate-reference-system-objects

```javascript
shapefile.read('example.shp')
    .then(data => {
        data.type
        data.bbox
        data.features
        data.crs //=> undefined
    })
```

There's going to be a `.prj` file associated with the shapefile files, might want to parse that and place that information into the GeoJSON `crs`. The projection file is a readable string.

```
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]
```

Proj4 does a good job at parsing these CRS codes:

https://github.com/proj4js/proj4js/blob/master/lib/parseCode.js

**Comment by mbostock** [comment]
I’d like to support this but I have no idea how to generate a valid CRS object in GeoJSON. I can use proj4js to parse the .prj file…

```js
var proj4 = require("proj4");

proj4.Proj(`GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]`);
```

But that only gets me half-way there, because I don’t know how to create a CRS object from the resulting *projection* instance.

**Comment by mbostock** [comment]
(I was also tempted to use [srs](https://github.com/mapbox/node-srs), but this depends on the gdal package, so there’s no way that’s running in a browser…)

**Comment by DenisCarriere** [comment]
I agree this would be quite a challenge, maybe it's best to place it in the documentation that states the data must be in WGS84. if no projection is found in the GeoJSON then it defaults to EPGS:4326, this would create incorrect coordinates if the shapefile is using a different projection.

**Comment by mbostock** [comment]
There’s nothing in here that requires that the input coordinates are WGS84, but it’s worth nothing that it’s the caller’s responsibility to assign the GeoJSON crs property if needed. I could add an argument to `shp2json` to let you set the output CRS, *e.g.*

```
shp2json --crs-name urn:ogc:def:crs:OGC:1.3:CRS84 input.shp
```

This would include a *crs* object like so in the output:

```json
"crs": {
  "type": "name",
  "properties": {
    "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
  }
}
```

**Comment by DenisCarriere** [comment]
That's a perfect solution, a user defined CRS would be an easy solution.

**Comment by mbostock** [comment]
Added in 0.5.6.

**Comment by knut-forkalsrud** [comment]
Forgive me for commenting on such an old ticket, but I can't help but think it would be easier to sidestep the whole "crs" object. I was trying to follow the steps of the excellent "command line cartography" tutorial, but ran straight into the problem with a different projection used in the shape files I have at hand. There was however a `.prj` file in the bundle, and I tried manually as input to [proj4js](http://proj4js.org/). As their documentation says "If only 1 projection is given then it is assumed that it is being projected from WGS84." I therefore used `inverse` to get the coordinates I was looking for. In code:
```
var proj = proj4('PROJCS["ETRS89_UTM_zone_33N_N_E",GEOGCS["GCS_ETRS_1989",DATUM["D_ETRS_1989",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",15],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["Meter",1]]');

console.log(proj.inverse([238944.15,6856464.7]));
// [10.052638464226415, 61.75176698509263]
```

I also notice that GeoJSON is now is now RFC 7946, and from what I can read in section 4 of that RFC, they have removed support for alternative coordinate reference systems altogether (https://tools.ietf.org/html/rfc7946#section-4).
