### ISSUE TITLE
Consistent error when running shp2json from the CLI

### ISSUE THREAD

**Issue by nickrttn** [mbostock/shapefile#30]
Everytime I run `shp2json` from the command line, I get the error

```
error: Decoder not present. Did you forget to include encoding-indexes.js first?
```

I've used `shp2json` with success before and this error only started occurring after a full reinstall of OSX. It happens on node 6.9.3 as well as 7.3 and 7.4.

Please let me know if there's any other information useful for debugging this.

**Comment by mbostock** [comment]
Unfortunately, I am not able to reproduce this error, so I don’t know how to investigate. I have filed inexorabletash/text-encoding#67 as this appears to be an issue with the text-encoding polyfill. Questions for you:

Did you install shp2json locally (`npm install shapefile`) or globally (`npm install -g shapefile`)?

If you installed it locally, what is the output of `npm ls`? If globally, `npm ls -g`?

How are you invoking shp2json? Are you specifying the `--encoding` argument? Are you passing a shapefile as the first argument, or are you piping a shapefile via stdin?

Do you have anything unusual in your Node setup, such as an alias that would pass default arguments to Node (say `--use-strict`)?

If you can reply over on inexorabletash/text-encoding#67 that would be helpful for debugging, or you can reply here and I will relay the information.

**Comment by nickrttn** [comment]
I've replied over at [inexorabletash/text-encoding#67](https://github.com/inexorabletash/text-encoding/issues/67). Just wanted to mention that downgrading text-encoding seems to have fixed the problem so it's likely a regression on their end.
