### ISSUE TITLE
Null value converted to a number

### ISSUE THREAD

**Issue by mhkeller** [mbostock/shapefile#31]
When I'm converting a shapefile that has a null value in its attribute table, I'm seeing that as a `0` in the resulting geojson. Here are the files and steps to replicate https://github.com/mhkeller/shapefile-bug

**Comment by mbostock** [comment]
I intend to investigate.

**Comment by mhkeller** [comment]
It seems that the property value for `avg_temp` is `'            '` for the null field. Exporting other shapefiles from QGIS looks like it gives null fields a value of `'**********'`. 

When this whitespace string is run through [dbf/number.js](https://github.com/mbostock/shapefile/blob/master/dbf/number.js), `+'            '` becomes `0` and the conditional is `false`, returning the `value` variable as `0`.

To catch this scenario you could add the following to number.js but I'm not familiar enough with the dbf spec to know if I have a faulty shapefile or whether this scenario should indeed be handled.

```
 if (value.trim() === '') {
   return null
 }
```

**Comment by mbostock** [comment]
Fixed in #32.
