### ISSUE TITLE
PolylineM/PolylineZ support

### ISSUE THREAD

**Issue by hwernstrom** [mbostock/shapefile#34]
Any plans to add PolylineM/PolylineZ support. I wouldn't care if it didn't return the M or Z values. Just the shapes(X Y). 

It would be easy to just add the type numbers, 13 and 23, to shp/index.js then call the readPolyLine function since all the M and Z values are after the Point X Y values.

**Comment by mbostock** [comment]
Sounds reasonable. I haven’t had time to work on it and I don’t have any test files with this geometry type. So, the first thing you could do would be to attach a few example files to this issue so that we have something to test against.

Take a look at #12 and #20 for earlier work.

**Comment by mbostock** [comment]
Fixed in 0.6.4!
