### ISSUE TITLE
Feed back - A build pain

### ISSUE THREAD

**Issue by Itee** [mbostock/shapefile#42]
Hello there !

First of all, thank for this package !

But... I was unable to build correctly the shapefile.js and shape.min.js
I try to build it using `npm run prepublishOnly` and i got some errors.

The first that i encountered is in the script pretest. the `rm` command is linux only ( sorry i'm under windows like 90% of people in the world 😩 ) maybe should you use a remover like [del-cli](https://github.com/sindresorhus/del-cli) in conjunction with [make-dir-cli](https://github.com/sindresorhus/make-dir-cli) for the folder creation. They are cross-platform.

The second was the command `cp` which is linux too... Maybe the usage of [cp-cli](https://www.npmjs.com/package/cp-cli) could help here too (cross-platform of course).

The third... `tail` same problem, maybe the same solution !

Then, the `$preamble` is not processed, so i got a `$(preamble)` in shapefile.js  on top...

Fiouu...

Lot of stuff that you do in prepublishOnly script could be integrated inside the rollup.config like uglifyjs part.

The only thing that i was unable to fix is the tail part for build test file. Which, IMO, could be bundled by rollup entirely with an other config file.

If you need some help to make this package more cross-platform, i could give you a little PR about.

Best regards,
Itee

**Comment by mbostock** [comment]
Thanks for the feedback. Unfortunately, I don’t currently have the time or motivation to support other development platforms. You are welcome to fork this repository and add Windows support.
