### ISSUE TITLE
Support multiple input files

### ISSUE THREAD

**Issue by stevage** [mbostock/shapefile#44]
It would be handy if multiple input files could work:

`shp2json *.shp > merged.json`

**Comment by mbostock** [comment]
Try [ndjson-cli](https://github.com/mbostock/ndjson-cli):

```
(for s in *.shp; do shp2json -n $s; done) | ndjson-reduce | ndjson-map '{type: "FeatureCollection", features: d}'
```

**Comment by stevage** [comment]
Would you accept a PR for this? I think the direct solution is so much cleaner than the workaround using Bash loops. It's also cross-platform :)
