### ISSUE TITLE
Reading from File / Blob?

### ISSUE THREAD

**Issue by thw0rted** [mbostock/shapefile#47]
Is there a simple way to turn a File (or Blob, I guess) from the browser into something that `shapefile.open` accepts?  Right now I'm using

    new Promise((resolve,reject) => {
        let reader = new FileReader();
        reader.onload = evt => resolve(reader.result);
        reader.readAsArrayBuffer(blob);
    });

which works, but of course this loses the benefit of working stream-wise.  It looks like WhatWG readable-streams support is pretty patchy, and focused on `fetch` rather than looking at local files.

If there is a better way to open from a local file (I get my File from `<input type="file">`), maybe an example in the docs would be helpful?  If not, maybe it would be worthwhile to add `Blob` as a supported argument?

**Comment by mbostock** [comment]
I’m not aware of a streaming API for reading from a File yet; the [Streams standard](https://streams.spec.whatwg.org/) is quite new and as far as I’m aware, only exposed via the Fetch API (as in my [streaming shapefile notebook](https://beta.observablehq.com/@mbostock/streaming-shapefiles)).

**Comment by thw0rted** [comment]
That lines up with what I've seen.  It's a shame, because I think at least for my application (based on Cesium JS), a lot of the public-data shapefiles I've seen (that range up in the hundreds of MB) would probably render OK but really tank performance if I try to shove them all into memory at once.  I'll see if I can do some more research...

**Comment by thw0rted** [comment]
A thought occurs to me: since Blobs must be of fixed length, and have a `slice` method, it *should* be possible to create a push-type ReadableStream implementation that wraps a Blob and "streams" out fixed-size chunks of it.  I'm not sure whether this would be worth the trouble, but maybe I'll file the idea away for later work.

**Comment by thw0rted** [comment]
It's been two and a half years and as far as I can tell there's still no standard for streaming data from local files.  I might just take a crack at rolling my own Blob wrapper...

ETA: apparently I just needed to read the last few tabs I opened before posting.  I found [this relatively recent new API in the File API working draft](https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream) and [this polyfill](https://github.com/MattiasBuelens/web-streams-polyfill#readme) that I think includes it for older browsers.

**Comment by mbostock** [comment]
File extends Blob, which can be used to construct a ReadableStream. Does that help?

https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream

**Comment by thw0rted** [comment]
Hah, I guess we were both reading the same thing at the same time -- your post showed up just as I saved my edit.  I'll report back once I see how this works out.

**Comment by thw0rted** [comment]
This worked exactly as expected.  Once you have a File (or any other Blob), the `stream` method resolves to a compatible stream, and the `open` method makes a Source just as the docs say.  I haven't tried the polyfill I linked to yet because I don't have any way to test in a browser that doesn't have native support at the moment, but I think it's safe to close this.
