### ISSUE TITLE
Reproject output to EPSG:4326 by default.

### ISSUE THREAD

**Issue by stevage** [mbostock/shapefile#50]
I really love shp2json (and avoiding the massive dependency that is GDAL), but the fact it doesn't support reprojection is often a pain. (Particularly when you write a script that assumes that all your shapefiles will be EPSG:4326, then one arrives in a different projection and now you have to switch to OGR2OGR or something.)

Mike [addressed the issue](https://github.com/mbostock/shapefile/issues/14), saying " This is just a Shapefile parser, so it wouldn’t be the right place to implement coordinate system transformations."

I would like to argue against this :)

First, it's not just a Shapefile parser. shp2json is clearly a Shapefile->Geojson converter. And currently, it's producing GeoJSON that doesn't comply with [the RFC](https://geojson.win). If a library or tool is producing GeoJSON as output, it should produce that GeoJSON in EPSG:4326  by default (and maybe allow retaining the original projection with some special flag).

Secondly, it definitely seems like the job of this library to parse the .prj file if there is one, at least.

Sure, it's possible to use workarounds to get around this limitation, but they're not convenient, particularly when you're dealing with a Shapefile whose projection you don't know ahead of time. That makes this kind of command line hard to write:

```
shp2json foo.shp | reproject --to=EPSG:4326 --from=...what?
```

(Supporting reprojection to arbitrary CRS's would definitely be beyond the scope of the library, otoh.)

**Comment by mbostock** [comment]
I’m not adding reprojection to this library. That would be a significant undertaking and I want this library to be small. Sorry!
