### ISSUE TITLE
Differing results between shapefile and mapshaper conversion

### ISSUE THREAD

**Issue by rdmurphy** [mbostock/shapefile#60]
I was loosely certain that #59 was the same issue I'm seeing, but now I'm not so sure and wanted to open a new issue just in case.

A link to the source shapefile: [wsp_120hr5km_latest.zip](https://github.com/mbostock/shapefile/files/3570889/wsp_120hr5km_latest.zip)

The shapefile in question is one of the [NHC's wind speed probabilities](https://www.nhc.noaa.gov/gis/) releases. It contains multiple concentric polygons that represent the different probabilities of winds. When I convert this shapefile with mapshaper (via the CLI, but also same result in the browser interface), it seems to come over correctly:

![image](https://user-images.githubusercontent.com/419145/64198482-26c0b080-ce3d-11e9-81a0-fc51d0f5faa8.png)
Output GeoJSON file is here: https://gist.github.com/rdmurphy/d283421b5b9cfa42f1fe29e390ce9230

But when I pass this same shapefile through `shapefile`, I get this:

![image](https://user-images.githubusercontent.com/419145/64198593-6daea600-ce3d-11e9-9d41-422ccdf376b7.png)
GeoJSON here: https://gist.github.com/rdmurphy/3a44e9be9736ec0364df6a926571b50a

Is this the same issue as #59, or something else?

And to be clear — totally understand if this is an accepted difference with how `shapefile` works! Just wasn't sure if perhaps I've surfaced a different issue.

Thank you!

**Comment by mbostock** [comment]
It looks like the winding order of these polygons is wrong (according to GeoJSON’s expectations):

https://observablehq.com/d/3263eaf199936bc7

It’s possible that MapShaper is correcting that for you, but this shapefile parser doesn’t do that. You should be able to fix this by reversing the coordinates of the some of the polygons and fixing the polygon-hole associations. But like #59 this isn’t really a bug in the parser, it’s just messy data that the parser isn’t fixing for you.

**Comment by rdmurphy** [comment]
Gotcha. 👍 That makes sense. I'll make sure that's cleared up in post-processing when I'm using `shapefile`. Got it work already with an extra pass with `geojson-rewind`: https://observablehq.com/d/4868d7d5d3d0732a

Thank you for taking a look! 👋

**Comment by mbostock** [comment]
If I have a moment I’ll see if there’s something smarter we can do with the input to correct the winding order. Thanks for including the test data.

**Comment by mbostock** [comment]
Folding into #64.
