### ISSUE TITLE
shapefile RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by jfoclpf** [mbostock/shapefile#67]
I have eight concurrent nodejs processes with [PM2](https://pm2.keymetrics.io/docs/usage/cluster-mode/) running each an app with this code:

```js
const shapefile = require('shapefile')
// ....
// ....
shapefile.read(
  path.join(__dirname, 'res', value.unzippedFilenamesWithoutExtension + '.shp'),
  path.join(__dirname, 'res', value.unzippedFilenamesWithoutExtension + '.dbf'),
  { encoding: 'utf-8' }
).then(geojson => {
  regions[key].geojson = geojson
  console.log(
    `Shapefiles read from ${colors.cyan(value.unzippedFilenamesWithoutExtension + '.shp')} ` +
    `and from ${colors.cyan(value.unzippedFilenamesWithoutExtension + '.dbf')}`
  )
  callback()
}).catch((error) => {
  console.error('Error reading shapefile', error.stack)
  callback(Error(error))
})
```
 
and this error is throwing ONLY at 2 of those 8 processes, it seems something colides on reading the files

```
/home/jfolpf/.pm2/logs/geoptapi-error-8.log last 15 lines:
8|geoptapi |     at wrapper (/var/www/geoptapi/node_modules/async/dist/async.js:268:20)
8|geoptapi |     at iterateeCallback (/var/www/geoptapi/node_modules/async/dist/async.js:413:21)
8|geoptapi |     at /var/www/geoptapi/node_modules/async/dist/async.js:321:20
8|geoptapi |     at /var/www/geoptapi/prepareServer.js:110:7
8|geoptapi | 10-07-2021: Error: Error: Error: Error: RangeError: Offset is outside the bounds of the DataView
8|geoptapi |     at /var/www/geoptapi/server.js:27:16
8|geoptapi |     at /var/www/geoptapi/prepareServer.js:18:9
8|geoptapi |     at /var/www/geoptapi/node_modules/async/dist/async.js:2955:19
8|geoptapi |     at wrapper (/var/www/geoptapi/node_modules/async/dist/async.js:268:20)
8|geoptapi |     at iterateeCallback (/var/www/geoptapi/node_modules/async/dist/async.js:413:21)
8|geoptapi |     at /var/www/geoptapi/node_modules/async/dist/async.js:321:20
8|geoptapi |     at /var/www/geoptapi/node_modules/async/dist/async.js:2953:17
8|geoptapi |     at /var/www/geoptapi/prepareServer.js:114:7
8|geoptapi |     at wrapper (/var/www/geoptapi/node_modules/async/dist/async.js:268:20)
8|geoptapi |     at iterateeCallback (/var/www/geoptapi/node_modules/async/dist/async.js:413:21)
```

do you have an idea of what might be?

**Comment by mahmoudadel54** [comment]
I get similar error too
Did you solve it ?

**Comment by jfoclpf** [comment]
Yes I did @mahmoudadel54 

I used [`async.retry`](https://caolan.github.io/async/v3/docs.html#retry)

Check my [implementation](https://github.com/jfoclpf/geoptapi/blob/main/prepareServer.js#L108):

```js
  async.forEachOf(regions, function (value, key, forEachOfCallback) {
    // try calling shapefile.read 5 times, waiting 500 ms between each retry
    // see: https://github.com/mbostock/shapefile/issues/67
    async.retry({ times: 5, interval: 500 }, function (retryCallback) {
      shapefile.read(
        path.join(__dirname, 'res', value.unzippedFilenamesWithoutExtension + '.shp'),
        path.join(__dirname, 'res', value.unzippedFilenamesWithoutExtension + '.dbf'),
        { encoding: 'utf-8' }
      ).then(geojson => {
        console.log(
          `Shapefiles read from ${colors.cyan(value.unzippedFilenamesWithoutExtension + '.shp')} ` +
          `and from ${colors.cyan(value.unzippedFilenamesWithoutExtension + '.dbf')}`
        )
        retryCallback(null, geojson)
      }).catch((err) => {
        retryCallback(Error(err))
      })
    }, function (err, result) {
      if (err) {
        forEachOfCallback(Error(err))
      } else {
        regions[key].geojson = result
        forEachOfCallback()
      }
    })
  }, function (err) {
    if (err) {
      mainCallback(Error(err))
    } else {
      mainCallback()
    }
  })
}
```

**Comment by mahmoudadel54** [comment]
> Yes I did @mahmoudadel54
> 
> I used [`async.retry`](https://caolan.github.io/async/v3/docs.html#retry)
> 
> Check my [implementation](https://github.com/jfoclpf/geoptapi/blob/main/prepareServer.js#L108):
> 
> ```js
>   async.forEachOf(regions, function (value, key, forEachOfCallback) {
>     // try calling shapefile.read 5 times, waiting 500 ms between each retry
>     // see: https://github.com/mbostock/shapefile/issues/67
>     async.retry({ times: 5, interval: 500 }, function (retryCallback) {
>       shapefile.read(
>         path.join(__dirname, 'res', value.unzippedFilenamesWithoutExtension + '.shp'),
>         path.join(__dirname, 'res', value.unzippedFilenamesWithoutExtension + '.dbf'),
>         { encoding: 'utf-8' }
>       ).then(geojson => {
>         console.log(
>           `Shapefiles read from ${colors.cyan(value.unzippedFilenamesWithoutExtension + '.shp')} ` +
>           `and from ${colors.cyan(value.unzippedFilenamesWithoutExtension + '.dbf')}`
>         )
>         retryCallback(null, geojson)
>       }).catch((err) => {
>         retryCallback(Error(err))
>       })
>     }, function (err, result) {
>       if (err) {
>         forEachOfCallback(Error(err))
>       } else {
>         regions[key].geojson = result
>         forEachOfCallback()
>       }
>     })
>   }, function (err) {
>     if (err) {
>       mainCallback(Error(err))
>     } else {
>       mainCallback()
>     }
>   })
> }
> ```

Not working 
Actually I am working on upload shp file and convert it to zipped shp file

**Comment by mahmoudadel54** [comment]
this is the piece of code I tried: 
  
` retry({ times: 5, interval: 500 }, function (retryCallback) {
      shapefile
        .open(file.name)
        .then((source) => {
          debugger;
          return source.read().then(function log(result) {
            if (result.done) return;
            console.log(result.value);
            return source.read().then(log);
          })
        }).catch((err) => {
          retryCallback(Error(err))
        })
        })
        .catch((error) => console.error(error.stack));`

**Comment by jfoclpf** [comment]
@mahmoudadel54  can you make your code readable?

**Comment by mahmoudadel54** [comment]
`
 retry({ times: 5, interval: 500 }, function (retryCallback) { 
        shapefile .open(file.name) .then((source) => {              // open shp file
 return source.read()                                                             // read source data
.then(function log(result) { 
if (result.done) return; 
console.log(result.value); 
return source.read().then(log); 
}
) })
.catch((err) => { retryCallback(Error(err)) })
 }) .catch((error) => console.error(error.stack));

`

**Comment by jfoclpf** [comment]
That's not readable

mahmoud adel ***@***.***> schrieb am Di., 28. Sep. 2021,
17:04:
